help:
	    @echo "_______BUILD ANGULAR FRONTEND______\n"
	    @echo "To build all apps run make make build-frontend"

build-frontend:
			@echo "Building local_auth"
	    ng build --project=local_auth --extract-css true
			@echo "Building dashboard"
			ng build --project=dashboard --extract-css true
			@echo "Building record_search"
			ng build --project=record_search --extract-css true
			@echo "Building transfer_owner"
			ng build --project=transfer_owner --extract-css true
			@echo "Building report"
			ng build --project=report --extract-css true
			@echo "Building manageRoles"
			ng build --project=manageRoles --extract-css true
			@echo "Building manageUsers"
			ng build --project=manageUsers --extract-css true
			@echo "Building export"
			ng build --project=export --extract-css true
			@echo "Building userProfile"
			ng build --project=userProfile --extract-css true
			@echo "Building dmp"
			ng build --project=dmp --extract-css true
			@echo "Building workspace_list"
			ng build --project=workspace_list --extract-css true

build-frontend-prod:
			@echo "Building local_auth"
	    ng build  --project=local_auth --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building dashboard"
			ng build  --project=dashboard --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building record_search"
			ng build  --project=record_search --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building transfer_owner"
			ng build  --project=transfer_owner --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building report"
			ng build  --project=report --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building manageRoles"
			ng build  --project=manageRoles --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building manageUsers"
			ng build  --project=manageUsers --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building export"
			ng build  --project=export --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building userProfile"
			ng build --project=userProfile --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building dmp"
			ng build --project=dmp --prod --build-optimizer --output-hashing=none --extract-css true
			@echo "Building workspace_list"
			ng build  --project=workspace_list --prod --build-optimizer --output-hashing=none --extract-css true

build-frontend-prod-sourcemaps:
			@echo "Building local_auth"
	    ng build  --project=local_auth --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building dashboard"
			ng build  --project=dashboard --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building record_search"
			ng build  --project=record_search --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building transfer_owner"
			ng build  --project=transfer_owner --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building report"
			ng build  --project=report --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building manageRoles"
			ng build  --project=manageRoles --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building manageUsers"
			ng build  --project=manageUsers --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building export"
			ng build  --project=export --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building userProfile"
			ng build --project=userProfile --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building dmp"
			ng build --project=dmp --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
			@echo "Building workspace_list"
			ng build  --project=workspace_list --prod --build-optimizer --output-hashing=none --sourcemaps=true --extract-css true
